### ISSUE TITLE
Error - A project with an Output Type of Class Library cannot be started directly

### ISSUE THREAD

**Issue by TheWizFX** [dennislwy/YahooFinanceAPI#2]
Hi

I'm new to C# and Microsoft visual studio, but I have downloaded your program and tried to run it directly, but get the error - A project with an Output Type of Class Library cannot be started directly. What am I doing wrong?

Best regards

**Comment by ooples** [comment]
You get the dll from the bin/debug folder after building this project and you add that dll as a reference to your existing project

**Comment by dennislwy** [comment]
@TheWizFX this project is a library class, you need to build (see build.bat) and add reference into your Windows Form project.
