### ISSUE TITLE
Multiple ticker download

### ISSUE THREAD

**Issue by TheWizFX** [dennislwy/YahooFinanceAPI#3]
Hi

I've got your coding working or rather I just pushed the right button;) anyway, I'm trying to download historical prices on a weekly interval back 365 days for several tickers at the same time, but after a couple of tickers, it will return and the following error
![image](https://user-images.githubusercontent.com/29316346/27029611-51d5cc06-4f69-11e7-8106-8bf6b12dbd38.png)
Is there some kind of limit to how many times you can download? And would it be possible to work around this, by renewing the crumb? And how would you do this?

Best regards

**Comment by dennislwy** [comment]
for multiple tickers download, it is advise to get a valid token first before starting your thread (or loop) to download historical prices on multiple tickers

```c#
  //first get a valid token from Yahoo Finance
  while (string.IsNullOrEmpty(Token.Cookie) || string.IsNullOrEmpty(Token.Crumb))
  {
    Token.Refresh();
  }

  // start your thread here to download multiple tickers historical price
```

hope this helps
