### ISSUE TITLE
How to download intradays?

### ISSUE THREAD

**Issue by ste71m** [dennislwy/YahooFinanceAPI#4]
Any idea how i can download intradays data?
I used 
http://chartapi.finance.yahoo.com/instrument/1.1/[TICKER]/chartdata;type=quote;range=5d/csv 
Now i tried with
https://query1.finance.yahoo.com/v7/finance/download/{0}?range=5d&interval=5m&crumb={1}
but not working as expected

**Comment by dennislwy** [comment]
this API is for EOD (end-of-day) data price, not for intradays
