### ISSUE TITLE
Unauthorized Code

### ISSUE THREAD

**Issue by kei2tahn** [dennislwy/YahooFinanceAPI#5]
At first, I would like to thank you for the code!
The code was working perfectly till yesterday, now the code in Historical.cs loops forever because the value in the if statement is **HttpStatusCode.Unauthorized**. The code gets a cookie value! Has Yahoo changed something in the api or is something in the code.

Looking forward to hearing from you. Thanking you in advance.

Panos Kourtesis

**Comment by dennislwy** [comment]
Probably you got a soft-ban from Yahoo. Remember to obtain a valid cookie and crumb before you send bunch of symbols request to their server.
Try wait 10-15mins and retry
