### ISSUE TITLE
request/question

### ISSUE THREAD

**Issue by ooples** [dennislwy/YahooFinanceAPI#6]
Wouldn't it be better and more effective to replace this line

csvData = wc.DownloadString(url);

with this:

csvData = await wc.DownloadStringAsync(url);

**Comment by dennislwy** [comment]
Async/Await is not supported in .NET3.5, but thats a very good suggestion, will upgrade it to .NET4.5 soon

**Comment by ooples** [comment]
Can you let me know when you upgrade it to .net 4.5?

**Comment by dennislwy** [comment]
@ooples code updated with Async
